package com.trainkraft.app.presentation

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.safeDrawing
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Surface
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.ListItem
import androidx.compose.material3.ListItemDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.hapticfeedback.HapticFeedbackType
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalHapticFeedback
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import com.kraft.ui.components.KraftTopBar
import com.kraft.ui.tokens.KraftSpacing
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Open-source licenses (Apache 2.0 section 4 attribution).
 *
 * Renders `assets/licenses.json`, generated by `tools/licenses/generate.py`
 * from the direct dependencies in `app/build.gradle.kts`. Each row shows the
 * artifact name, version, and license chip; tapping expands the full license
 * name + project URL. A missing/unreadable asset renders an explanatory
 * empty state instead of crashing.
 */
@Serializable
data class LicenseEntry(
    val name: String,
    val version: String,
    val license: String,
    val url: String = "",
    val testOnly: Boolean = false,
)

private val licensesJson = Json { ignoreUnknownKeys = true }

@Composable
fun LicensesScreen(onBack: () -> Unit) {
    val haptics = LocalHapticFeedback.current
    val context = LocalContext.current
    val entries = remember(context) { loadLicenses(context) }

    Scaffold(
        topBar = {
            KraftTopBar(
                title = "Open-source licenses",
                navigationIcon = {
                    IconButton(onClick = {
                        haptics.performHapticFeedback(HapticFeedbackType.TextHandleMove)
                        onBack()
                    }) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
            )
        },
        contentWindowInsets = WindowInsets.safeDrawing,
    ) { paddingValues ->
        if (entries == null) {
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(paddingValues)
                    .padding(
                        horizontal = KraftSpacing.Spacing16,
                        vertical = KraftSpacing.Spacing8,
                    ),
            ) {
                Text(
                    text = "License list unavailable",
                    style = MaterialTheme.typography.titleMedium,
                    color = MaterialTheme.colorScheme.onSurface,
                )
                Spacer(modifier = Modifier.height(KraftSpacing.Spacing8))
                Text(
                    text = "The licenses file is missing from this build. " +
                        "Regenerate it with tools/licenses/generate.py.",
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
        } else {
            LazyColumn(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(paddingValues),
                contentPadding = PaddingValues(
                    start = KraftSpacing.ScreenEdge,
                    end = KraftSpacing.ScreenEdge,
                    top = KraftSpacing.Spacing8,
                    bottom = KraftSpacing.Spacing16,
                ),
                verticalArrangement = Arrangement.spacedBy(KraftSpacing.Spacing12),
            ) {
                // Shipped libraries first, test-only ones last (generator sorts).
                item(key = "intro") {
                    Text(
                        text = "TrainKraft stands on these open-source libraries. " +
                            "Test-only helpers are listed last and do not ship in the app.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        modifier = Modifier.padding(
                            horizontal = KraftSpacing.Spacing4,
                            vertical = KraftSpacing.Spacing4,
                        ),
                    )
                }
                item(key = "group") {
                    Surface(
                        shape = MaterialTheme.shapes.large,
                        color = MaterialTheme.colorScheme.surfaceContainerLow,
                        modifier = Modifier
                            .fillMaxWidth()
                            .cardOutline(MaterialTheme.shapes.large),
                    ) {
                        Column {
                            entries.forEachIndexed { index, entry ->
                                LicenseRow(entry = entry)
                                if (index != entries.lastIndex) {
                                    HorizontalDivider(
                                        modifier = Modifier.padding(
                                            start = KraftSpacing.Spacing16,
                                        ),
                                    )
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun LicenseRow(entry: LicenseEntry) {
    var expanded by remember { mutableStateOf(false) }
    val haptics = LocalHapticFeedback.current
    ListItem(
        headlineContent = {
            Text(
                text = entry.name,
                style = MaterialTheme.typography.bodyLarge.copy(
                    fontFamily = FontFamily.Monospace,
                ),
            )
        },
        supportingContent = {
            Column {
                Text(
                    text = entry.version + if (entry.testOnly) " · test-only" else "",
                    style = MaterialTheme.typography.bodySmall.copy(
                        fontFeatureSettings = "tnum",
                    ),
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
                if (expanded) {
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                        text = entry.license,
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurface,
                    )
                    if (entry.url.isNotBlank()) {
                        Text(
                            text = entry.url,
                            style = MaterialTheme.typography.bodySmall.copy(
                                fontFamily = FontFamily.Monospace,
                            ),
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                    }
                }
            }
        },
        trailingContent = {
            Surface(
                shape = MaterialTheme.shapes.extraLarge,
                color = MaterialTheme.colorScheme.secondaryContainer,
                contentColor = MaterialTheme.colorScheme.onSecondaryContainer,
                modifier = Modifier.cardOutline(MaterialTheme.shapes.extraLarge),
            ) {
                Text(
                    text = shortLicense(entry.license),
                    style = MaterialTheme.typography.labelMedium,
                    modifier = Modifier.padding(horizontal = 12.dp, vertical = 6.dp),
                )
            }
        },
        colors = ListItemDefaults.colors(
            containerColor = MaterialTheme.colorScheme.surfaceContainerLow,
        ),
        modifier = Modifier
            .fillMaxWidth()
            .heightIn(min = 56.dp)
            .clickable(
                role = Role.Button,
                onClickLabel = if (expanded) "Collapse license details" else "Expand license details",
            ) {
                haptics.performHapticFeedback(HapticFeedbackType.TextHandleMove)
                expanded = !expanded
            },
    )
}

private fun shortLicense(license: String): String = when {
    license.startsWith("Apache License", ignoreCase = true) -> "Apache 2.0"
    license.startsWith("MIT", ignoreCase = true) -> "MIT"
    license.startsWith("Eclipse Public", ignoreCase = true) -> "EPL 1.0"
    license.startsWith("First-party", ignoreCase = true) -> "In-house"
    license.startsWith("Android Software Development", ignoreCase = true) -> "Google SDK"
    license.startsWith("Unknown", ignoreCase = true) -> "Verify"
    else -> license.take(12)
}

private fun loadLicenses(context: android.content.Context): List<LicenseEntry>? =
    runCatching {
        context.assets.open("licenses.json").bufferedReader().use { reader ->
            licensesJson.decodeFromString<List<LicenseEntry>>(reader.readText())
        }
    }.getOrNull()
